-- Run in Supabase SQL Editor for project nfgoyspfbcpnlrpmxpgv (once)
-- if public.job_applications is not present yet.

CREATE TABLE IF NOT EXISTS public.job_applications (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TEXT NOT NULL,
  job_url       TEXT,
  job_text      TEXT NOT NULL,
  resume_choice TEXT,
  job_title     TEXT,
  salary        TEXT,
  job_summary   TEXT
);

ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.job_applications FROM anon, authenticated, PUBLIC;

COMMENT ON TABLE public.job_applications IS
  'Job app tracker (FastAPI) — server uses DATABASE_URL; not for anon Data API.';
